name: Deploy to Azure VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to VM
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          source: "."
          target: "/home/${{ secrets.AZURE_VM_USER }}/app"

      - name: Set up .env and run deploy script on VM
        uses: appleboy/ssh-action@v0.1.6
        env:                     
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AZURE_SQL_DB:   ${{ secrets.AZURE_SQL_DB }}
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          
          envs: |
            OPENAI_API_KEY
            AZURE_SQL_DB
          
          script: |
            cd /home/${{ secrets.AZURE_VM_USER }}/app
            touch .env

            update_env () {
              KEY="$1"; VALUE="$2"
              grep -q "^${KEY}=" .env 2>/dev/null \
              && sed -i "s|^${KEY}=.*|${KEY}=\"${VALUE}\"|" .env \
              || echo "${KEY}=\"${VALUE}\"" >> .env
            }

            update_env OPENAI_API_KEY "$OPENAI_API_KEY"
            update_env AZURE_SQL_DB   "$AZURE_SQL_DB"

            chmod 600 .env

            sudo systemctl restart fincofella.service

